-- MySQL Script generated by MySQL Workbench
-- Sat Jan 30 15:06:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GéoCaches
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GéoCaches
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GéoCaches` DEFAULT CHARACTER SET utf8 ;
USE `GéoCaches` ;

-- -----------------------------------------------------
-- Table `GéoCaches`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GéoCaches`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GéoCaches`.`Cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GéoCaches`.`Cache` (
  `idCache` INT NOT NULL AUTO_INCREMENT,
  `GPS` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `type` ENUM("cache traditionnelle", "cache jeu de piste", "cache objet", "cache objet voyageur") NOT NULL,
  `nature` ENUM("physique", "virtuelle") NOT NULL,
  `etat` ENUM("activée", "en cours d’activation", "fermée", "suspendue") NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idCache`),
  INDEX `fk_Cache_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Cache_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `GéoCaches`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GéoCaches`.`Visite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GéoCaches`.`Visite` (
  `idVisite` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `photo` VARCHAR(45) NULL,
  `decouverte` INT NOT NULL DEFAULT 0,
  `commentaire` VARCHAR(1000) NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  `Cache_idCache` INT NOT NULL,
  PRIMARY KEY (`idVisite`),
  INDEX `fk_Visite_Utilisateur_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  INDEX `fk_Visite_Cache1_idx` (`Cache_idCache` ASC) VISIBLE,
  CONSTRAINT `fk_Visite_Utilisateur`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `GéoCaches`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visite_Cache1`
    FOREIGN KEY (`Cache_idCache`)
    REFERENCES `GéoCaches`.`Cache` (`idCache`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
